> png(filename="plot4.png",width = 480,height = 480)
> par(mfrow=c(2,2))
> plot(df$timestamp,df$Global_active_power,type="l",xlab="",ylab="Global Active Power")
> plot(df$timestamp,df$Voltage,type="l",xlab="datetime",ylab="Voltage")
> plot(df$timestamp,df$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering",col="black")
> lines(df$timestamp,df$Sub_metering_2,type="l",col="red")
> lines(df$timestamp,df$Sub_metering_3,type="l",col="blue")
> legend("topright",col=c("black","red","blue"),c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lwd=1)
> plot(df$timestamp,df$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
> dev.off()